$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$source = Get-Content -LiteralPath (Join-Path $root 'lara/kexploit/WZHUDBridge.mm') -Raw -Encoding UTF8
$project = Get-Content -LiteralPath (Join-Path $root 'lara.xcodeproj/project.pbxproj') -Raw -Encoding UTF8
foreach ($framework in @('MetalKit','Metal')) {
    if ($project -notmatch "name = $framework\.framework; path = System/Library/Frameworks/$framework\.framework; sourceTree = SDKROOT" -or
        $project -notmatch "PBXFrameworksBuildPhase;[\s\S]*?$framework\.framework in Frameworks") {
        throw "FAIL: $framework.framework is not explicitly linked"
    }
}

function Require([string]$pattern, [string]$message) {
    if ($source -notmatch $pattern) { throw "FAIL: $message" }
}
function Reject([string]$pattern, [string]$message) {
    if ($source -match $pattern) { throw "FAIL: $message" }
}

# Yuanbao/Qingtian menu policy: drawing controls remain point-for-point on the
# first page, while the real aim runtime owns the two additional pages.
Require 'qingtian_layout_for_bounds' 'Qingtian responsive layout is missing'
Require 'availableWidth=phone \? width\*\.80' 'Qingtian phone width policy changed'
Require 'baseWidth=phone \? fmin\(780,fmax\(540,availableWidth\)\)' 'Qingtian width clamp changed'
Require '@\[@"绘制",@"\\u81ea\\u7784",@"\\u81ea\\u7784\\u8c03\\u8bd5"\]' 'Qingtian/aim page order changed'
Require '@"绘制设置"' 'Qingtian drawing page title missing'
Require '@"屏幕元素与位置调整"' 'Qingtian drawing subtitle missing'
Require '@"设置即时生效"' 'Qingtian footer state missing'
Require '@"退出 HUD"' 'AX exit action missing'
Require 'setTitle:@"×"' 'Panel-only close button is missing'
Require 'kWZHUDControlHide' 'Panel-only close action is missing'
Require 'set_panel_visible_main\(NO\)' 'Panel-only close does not collapse to the floating button'
Require 'g_floatButton\.layer\.cornerRadius=20' 'AX floating button is not circular'
Require 'clamp_float_center' 'Floating control is not clamped to logical bounds'
Require 'g_floatSavedCenter\.x/CGRectGetWidth\(oldLogical\)\*CGRectGetWidth\(logical\)' 'Floating control is not normalized across rotation'
Require 'center\.y=fmin\(CGRectGetHeight\(logical\)-half,fmax\(half,center\.y\)\)' 'Floating control can remain outside landscape bounds'
Require 'commit_menu_window_geometry_main\(\);[\s\S]{0,80}\[CATransaction flush\]' 'Rotated menu geometry is not committed to the hosted context'
Reject 'CGRectMake\(0,\s*0,\s*900,\s*600\)|wzCore|@"CORE\.|S M O B A|WZHUDTouchProxy|update_fallback_snapshot|present_snapshot_metal' 'CORE presentation residue present'
Reject 'NSUserDefaults' 'AX settings incorrectly use UserDefaults'

foreach ($title in @('调试窗口','屏幕捕获','大图头像','小图兵线',
                    '小图头像','野怪刷新','英雄技能','英雄方框',
                    '屏幕绘制','位置与视距','恢复位置',
                    '技能 X','技能 Y','地图 X','地图 Y',
                    '进阶兼容 · 自动功能','斩杀敌人','设置坐标',
                    '进阶兼容 · 视野','兵线暴露','英雄暴露','敌人视野',
                    '参数与运行时','选择目标','目标绘制','英雄与模式','技能参数')) {
    Require ([regex]::Escape('@"' + $title + '"')) "AX control missing: $title"
}
Reject '@"大地图射线"|@"小地图血量"|@"小地图回城"' 'Non-Yuanbao independent drawing toggles remain'
Require 'wzax_touch_is_ready\(\)' 'External touch sender readiness is not surfaced'
Require '@"\u6280\u80fd\u69fd\u4f4d",@\[@"1",@"2",@"3",@"4"\]' 'Aim skill slot is not an explicit 1..4 choice'
Require '@"\u6821\u51c6\u771f\u5b9e\u6280\u80fd\u62d6\u62fd"' 'Real skill-drag calibration control is missing'
Require '@"\\u81ea\\u7784\\u5f00\\u5173",44000,ax_bool\(@"aim\.enabled"\),YES' 'Aim cannot be armed before first gesture verification'
Reject 'aim\.button|44003|AIM 悬浮按钮' 'Unconnected AIM floating trigger remains as a fallback UI'
Require 'defaults\[\] = \{[\s\S]{0,80}16,-57,10,150,MAX\(0\.0f,logicalWidth-150\.0f-10\.0f\)' 'Yuanbao coordinate defaults changed'
Require 'minima\[\] = \{0,-300,0,0,0\}' 'Yuanbao skill X slider cannot represent -57'
Require 'if \(ax_bool\(@"bigmapimage"\)\) flags \|= WZESP_SHOW_AVATAR' 'heroEnabled is not bound to the world portrait consumer'
Reject 'WZESP_SHOW_RAY' 'Legacy all-hero ray implementation remains beside aim target drawing'
Require 'if \(ax_bool\(@"draw"\)\)[\s\S]{0,100}WZESP_SHOW_MINIMAP \| WZESP_SHOW_HEALTH \| WZESP_SHOW_RECALL' 'avatarEnabled is not bound to minimap portrait/health/recall'
Require 'g_captureProtected\.store\(ax_bool\(@"stream"\)\)' 'liveBypassEnabled is not bound to capture protection'
Require 'ax_bool\(@"debug"\)[^;]*WZESP_SHOW_MAP_ADJUSTMENT' 'debugOverlayEnabled consumer is missing'
Require 'WZESP_SHOW_MAP_ADJUSTMENT\)[\s\S]{0,240}ax_push_rect\(commands,[\s\S]{0,180}config\.minimapSize' 'Debug guide is not emitted by the shared renderer'
Reject 'g_wzMinimapGuide|apply_wz_snapshot_main|g_wzWorldViews|g_wzRayViews|g_wzSkillPortraits' 'Legacy UIKit staging renderer remains beside the shared command renderer'
Require 'ax_bool\(@"soldier"\)[^;]*WZESP_SHOW_SOLDIER' 'soldierEnabled consumer is missing'
Require 'ax_bool\(@"monster"\)[^;]*WZESP_SHOW_MONSTER \| WZESP_SHOW_MONSTER_TIMER' 'monsterEnabled consumer is missing'
Require 'ax_bool\(@"skill"\)[^;]*WZESP_SHOW_SKILL' 'skillEnabled consumer is missing'
Require 'ax_bool\(@"box"\)[^;]*WZESP_SHOW_BOX' 'boxEnabled consumer is missing'
Require '\[key isEqualToString:@"draw"\][\s\S]{0,100}\[key isEqualToString:@"monster"\]' 'OwnFeatureConfig default toggles changed'
Require 'tag==43000[\s\S]{0,400}@"skill\.x",@\(-57\)[\s\S]{0,200}@"skill\.y",@\(10\)[\s\S]{0,200}@"mapsize",@\(139\)[\s\S]{0,200}@"mapx",@\(52\)' 'OwnQingtian restore-position values changed'

# Keychain service: 0x10001d370; read: 0x10000ccd8; write: 0x10000fe1c.
Require 'stringByAppendingString:@"\.ax-settings"' 'AX settings service suffix changed'
Require 'kSecAttrAccount:@"settings"' 'AX settings account changed'
Require 'kSecMatchLimitOne' 'AX settings query does not request one result'
Require 'NSPropertyListBinaryFormat_v1_0' 'AX settings binary plist encoding missing'
Require 'kSecAttrAccessibleAfterFirstUnlock' 'AX keychain accessibility changed'
Require 'SecItemUpdate[\s\S]{0,200}errSecItemNotFound[\s\S]{0,250}SecItemAdd' 'AX keychain update/add sequence changed'
Require 'ax_bool\(@"auto\.kill"\)[^;]*WZESP_AUTO_KILL' 'Auto-kill UI is not bound to its action flag'
Require 'ax_bool\(@"shiye\.hero"\)[^;]*WZESP_SHOW_HERO_VISION' 'Hero exposure UI is not bound to its collector flag'
Require 'ax_bool\(@"shiye\.soldier"\)[^;]*WZESP_SHOW_SOLDIER_VISION' 'Soldier exposure UI is not bound to its collector flag'
Require 'ax_bool\(@"minimap\.enemyvision"\)[^;]*WZESP_SHOW_ENEMY_VISION' 'Enemy minimap vision UI is not bound to its collector flag'
Require 'g_captureKillPoint && phase==WZHUDPointerPhaseBegan[\s\S]{0,800}click_coord_x[\s\S]{0,500}click_coord_y[\s\S]{0,500}ax_store_setting\(@"click_coord_space",@"fixed"\)' 'Physical kill coordinate capture is not persisted'
Require 'objc_getClass\("FBSOrientationObserver"\)' 'AX orientation observer missing'
Require 'NSSelectorFromString\(@"activeInterfaceOrientation"\)' 'AX authoritative orientation getter missing'
Require 'FrontBoardServices\.framework/FrontBoardServices' 'FrontBoardServices is not loaded before creating the orientation observer'
Require 'UIInterfaceOrientationLandscapeLeft: return \(CGFloat\)-M_PI_2' 'Landscape-left rotation is reversed'
Require 'UIInterfaceOrientationLandscapeRight: return \(CGFloat\)M_PI_2' 'Landscape-right rotation is reversed'
Reject 'if \(g_orientation==orientation\) return;' 'Repeated orientation sync still skips geometry refresh'
Require 'g_orientation==orientation &&[\s\S]{0,160}CGRectEqualToRect\(g_orientationSurfaceBounds,physical\)[\s\S]{0,160}CGRectEqualToRect\(g_orientationLogicalBounds,logical\)' 'Same-orientation sync does not refresh changed surface geometry'
Require 'g_captureProtected\.store\(ax_bool\(@"stream"\)\)' 'Live-stream capture policy is not backed by the stream setting'
Require 'g_captureProtected\.load\(\) \? 0x12 : 0' 'Capture mask is not disabled by default and enabled only for live-stream protection'
Require 'g_hidActivePointerIDs\.insert\(value\.longLongValue\)\.second' 'Global HID chord does not track distinct pointer identities'
Require 'g_hidActivePointerIDs\.size\(\) >= 3[\s\S]{0,180}!g_hidThreeFingerLatched' 'Third distinct HID pointer does not latch once'
Require 'set_panel_visible_main\(!g_panelVisible\)' 'Global HID three-finger chord does not toggle the AX panel'
Require 'phase == WZHUDPointerPhaseEnded \|\|[\s\S]{0,100}phase == WZHUDPointerPhaseCancelled[\s\S]{0,180}g_hidActivePointerIDs\.erase' 'HID pointer identities are not cleared on end/cancel'
Reject 'CMMotionManager|orientation_poll_timer|core_|wzCore' 'Non-AX orientation/input implementation remains'

# CA renderer: 0x10074d6b0..0x1007666a8. No full-frame snapshot bridge.
Require 'MTLPixelFormatRGBA8Unorm' 'AX per-image texture format changed'
Require 'kCGBitmapByteOrder32Big\|kCGImageAlphaPremultipliedLast' 'AX image bitmap format changed'
Require 'objc_setAssociatedObject\(texture,&kAXTextureImageKey,image,OBJC_ASSOCIATION_RETAIN_NONATOMIC\)' 'CA image association lifetime missing'
Require 'kWZHUDControlPanelDrag' 'Background sidebar drag state missing'
Require 'move_panel_main\(\[gesture translationInView:g_menuCanvas\]\)' 'UIKit/HID panel geometry no longer shared'
Require 'NSTimeInterval duration=\.3' 'AX observer fallback animation duration changed'
Require '@\[@"orientation",@"duration"\]' 'AX observer update fields missing'
Require 'item.screenY - 50\.0' 'AX world box offset changed'
Require 'const float centerY = item\.screenY - 20\.0f' 'Yuanbao world portrait anchor changed'
Require 'const float portraitRadius = 6\.0f' 'Yuanbao world portrait radius changed'
Require 'ax_push_circle\(commands, center, 7\.8f' 'Yuanbao world health circle missing'
Require 'const float radius = showMapHero \? 8\.0f' 'Yuanbao minimap health-ring radius changed'
Require 'constexpr float portraitRadius = 6\.0f' 'Yuanbao minimap portrait radius changed'
Require 'ax_push_circle\(commands, center, radius,[\s\S]{0,80}0x40000000u, false, 2\.4f\)' 'Yuanbao minimap health-ring geometry changed'
Require 'ax_push_arc\(commands, center, radius, 0\.0f,[\s\S]{0,100}0xF2303BFFu, 2\.4f\)' 'Yuanbao minimap health arc color changed'
Reject 'ax_yuanbao_health_gradient' 'Skill-only health gradient leaked into the minimap avatar ring'
Require 'item\.enemy && item\.configId > 0' 'Minimap portraits are not restricted to valid enemy heroes'
Require 'if \(!wz_hero_portrait\(item\.configId\)\) continue;' 'A missing portrait can still publish a blank minimap ring'
Reject 'showMapHero \? config\.minimapSize / 17\.0f' 'AX-scaled minimap portrait remains beside Yuanbao fixed geometry'
Require '24\.0f\*skillIndex' 'Yuanbao skill-row spacing changed'
Require 'CGRectMake\(x-8,y-8,16,16\),8' 'Yuanbao skill portrait size changed'
Require 'CGRectMake\(x-12,y-26\.2f,24,14\)' 'Yuanbao auxiliary cooldown anchor changed'
Require 'ax_push_image\(commands,item\.skillConfigId,true,summonerFrame,4\)' 'Yuanbao summoner icon rounding changed'
Require 'kAXImGuiDeltaTime = 0\.01666666753590107f' 'AX ImGui default DeltaTime changed'
Require 'g_axFrameTime \+= \(double\)kAXImGuiDeltaTime' 'AX animation Time no longer uses the fixed ImGui step'
Reject 'g_axLastTick|now-g_axLastTick' 'Wall-clock delta path remains in the AX animation clock'
Require '@interface WZAXMetalRenderer : NSObject <MTKViewDelegate>' 'Foreground Metal delegate missing'
Require 'id<MTLCommandQueue> _commandQueue' 'Foreground command queue missing'
Require 'drawInMTKView:' 'Foreground drawable rendering missing'
Require 'ImGui_ImplMetal_NewFrame\(pass\)' 'Dear ImGui Metal new-frame path missing'
Require 'ImGui::NewFrame\(\)' 'Dear ImGui draw-list frame missing'
Require 'buildDirectDrawList:ImGui::GetBackgroundDrawList\(\)' 'AX snapshot producer is not feeding an ImGui draw list directly'
Require 'ax_build_render_commands\(latest, latestCount, current_wz_config\(\)' 'Shared immutable snapshot command producer is missing'
Require 'submitCommands:&frame\.commands' 'Foreground does not consume the shared immutable snapshot commands'
Require 'ImGui_ImplMetal_RenderDrawData\(ImGui::GetDrawData\(\),command,encoder\)' 'Dear ImGui Metal draw-data submission missing'
Require 'drawList->AddText' 'ImGui glyph triangulation path missing'
Require 'drawList->AddImageRounded' 'ImGui texture/rounded-image path missing'
Reject 'textureForCommand|setVertexBytes:vertices|drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:6|CGPathApply|for \(CALayer \*layer in _commands\)' 'Legacy per-layer/CGPath foreground translation remains'
Require 'if \(!rendererReady\) \{\s*set_error\([^;]+;\s*return NO;' 'Renderer creation failure is published as active'
Require 'if \(!create_hud_main\(\)\) \{[\s\S]{0,100}g_requested\.store\(false\);[\s\S]{0,80}destroy_hud_main\(\)' 'Failed startup does not close requests and roll back local windows'
Require '\[command presentDrawable:drawable\]' 'Foreground drawable presentation missing'
Require '\[command commit\]' 'Foreground command buffer commit missing'
Require 'g_metalRenderer\.view\.hidden=NO' 'Foreground ImGui view is not made visible'
Require 'g_metalRenderer\.view\.hidden=YES' 'Background does not hide the Metal view'
Require '\[g_layerRenderer setVisible:NO\]' 'CA backend is not hidden in foreground'
Require '\[g_layerRenderer setVisible:YES\]' 'CA backend is not restored in background'
Require 'orientationGeneration!=g_orientationGeneration.load\(\)' 'Stale rotation completion is not generation guarded'
Require 'const float rotation = \(float\)frameTime \* 2\.5f' 'AX recall spin rate changed'
Require 'segment < 4' 'AX four recall arc groups missing'
Require '1\.0995573997497559f' 'AX primary recall sweep changed'
Require '0\.5497786998748779f' 'AX secondary recall sweep changed'
Require '0xFFFFDC64u' 'AX primary recall color changed'
Require '0xB4C87828u' 'AX secondary recall color changed'
Require '0x50DC8C3Cu' 'AX recall base-ring color changed'
Require 'AXMonsterPolicy::MinimapMarker' 'AX fixed-slot monster marker policy missing'
Require 'item.axMonsterSlot' 'Monster slot identity is lost across collection/rendering'
Require 'AXMonsterPolicy::TimerColor\([\s\S]{0,60}\(size_t\)item.axMonsterSlot\)' 'AX timer color is not consumed from shared policy'
Require 'AXMonsterPolicy::DrawableSlot\(item.axMonsterSlot\)' 'AX draw-slot filter is not consumed from shared policy'
Require 'AXMonsterPolicy::TimerOriginOffset' 'AX timer origin offset missing'
Require 'item.cooldownSeconds != 0' 'AX nonzero timer condition changed'
Reject 'WZYuanbaoDrawPolicy|monsterSubtype|showWorldMonster' 'Non-AX monster presentation remains'
Require '@implementation AXHUDCoreAnimationRenderer' 'AX CA renderer missing'
Require 'object_getClass\(layer\) != layerClass' 'Layer pool does not compare exact layer class'
Require '@"AXHUDBackgroundContent"' 'AX CA root name changed'
Require '@"Rajdhani-Bold"' 'AX font missing'
Require 'ax_hero_cache_path' 'Yuanbao persistent hero cache path is missing'
Require 'dataWithContentsOfFile:cachePath' 'Yuanbao hero disk cache is not read before download'
Require 'attempt<3 && !image\.CGImage' 'Yuanbao image retry is not decode-driven'
Require 'writeToFile:cachePath atomically:YES' 'Downloaded Yuanbao portraits are not persisted'
Require 'summonero/%d\.png' 'Yuanbao summoner icon URL changed'
Require 'CFAbsoluteTimeGetCurrent\(\)\+5\.0' 'AX image failure cooldown changed'
Require '\(width-112\.0f\)\*\.5f\+config\.skillX\+[\s\S]{0,50}24\.0f\*skillIndex' 'Yuanbao skill anchor/spacing changed'
Require 'const float y=config\.skillY\+20\.0f' 'Yuanbao skill Y anchor changed'
Require 'CGRectMake\(x-8,y-8,16,16\)' 'Yuanbao hero skill portrait size changed'
Require 'CGRectMake\(x-8,y\+16,16,16\)' 'Yuanbao summoner icon offset changed'
Require 'wzax_touch_start\(\)' 'AX touch sender is never started by the HUD'
Require 'wzax_touch_set_host\(remoteCall\)' 'SpringBoard-hosted HUD does not bind its verified touch transport'
Require 'const BOOL useLayerRenderer = backgroundHosted \|\| remoteHosted \|\|[\s\S]{0,80}!g_localHostingReady\.load\(\)' 'Remote/unhosted draw surfaces can still select an unavailable Metal drawable'
Require 'kCALineCapButt' 'AX default line cap changed'
Require 'kCALineJoinRound' 'AX default line join changed'
Require 'kCAGravityResizeAspectFill' 'AX image gravity changed'
Require 'CGRectInset\(anchor,\s*-4,\s*-4\)' 'AX compact interaction padding changed'
Require 'wantsCompact = !wzhud_springboard_hosting_ready\(\) &&[\s\S]{0,160}!g_panelVisible && !g_hudContentRequiresFullScreen &&[\s\S]{0,120}!hud_pointer_active\(\) && !hud_geometry_transitions_active\(\)' 'Hosted menu context can still collapse and clip the floating button'
Require 'g_hudCompactGeometryApplied = wantsCompact' 'Compact geometry state is not recorded'
Require 'visible \? \.22 : \.18' 'AX panel animation duration changed'
Require 'CGAffineTransformMakeScale\(\.94,\.94\)' 'AX panel animation scale changed'
Require 'for \(double delay : \{\.15,\.65,1\.5\}\)' 'AX app-switch orientation retries changed'

Write-Output 'PASS: AX 1.2.8 UI static contracts; UIKit/device behavior remains unverified'
