$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot

function Require-Text([string]$Path, [string]$Pattern, [string]$Message) {
    $content = Get-Content -LiteralPath (Join-Path $root $Path) -Raw
    if ($content -notmatch $Pattern) {
        throw "FAIL: $Message ($Path)"
    }
}

function Reject-Text([string]$Path, [string]$Pattern, [string]$Message) {
    $content = Get-Content -LiteralPath (Join-Path $root $Path) -Raw
    if ($content -match $Pattern) {
        throw "FAIL: $Message ($Path)"
    }
}

function Require-Count([string]$Path, [string]$Pattern, [int]$Count, [string]$Message) {
    $content = Get-Content -LiteralPath (Join-Path $root $Path) -Raw
    $actual = [regex]::Matches($content, $Pattern).Count
    if ($actual -ne $Count) {
        throw "FAIL: $Message expected=$Count actual=$actual ($Path)"
    }
}

Require-Text 'lara/kexploit/wzmem.h' 'WZ_CAP_READ' '缺少统一读取 capability'
Require-Text 'lara/kexploit/wzmem.h' 'WZ_CAP_WRITE' '缺少统一写入 capability'
Require-Text 'lara/kexploit/wzmem.m' 'wz_try_mach_connect\(name, generation\).*return true' 'Mach task 未作为首选传输'
Require-Text 'lara/kexploit/wzmem.m' 'task_read_for_pid' '缺少只读 task port 获取回退'
Require-Text 'lara/kexploit/wzmem.m' 'processor_set_tasks' '缺少 Core processor-set task port 回退'
Require-Text 'lara/kexploit/wzmem.m' 'task_threads\(' '缺少 Core task 线程只读探测'
Require-Text 'lara/kexploit/wzmem.m' 'mach_port_deallocate\(mach_task_self\(\), threads\[index\]\)' '线程端口未逐个释放'
Require-Text 'lara/kexploit/wzmem.m' 'wz_try_mach_connect_pid\(name, pid, proc, generation\)' '未使用内核确认的 PID 重试 Mach 传输'
Require-Text 'lara/kexploit/wzmem.m' 'mach_port_deallocate\(mach_task_self\(\), machTask\)' '断开未释放 task port'
Require-Text 'lara/kexploit/wzmem.m' 'region walk 后目标身份失效' 'Mach region walk 后未复核目标身份'
Require-Text 'lara/kexploit/wzmem.m' 'writing \? WZ_CAP_WRITE : WZ_CAP_READ' '读写未按 capability 门禁'
Require-Text 'lara/kexploit/wzmem.m' 'wzmem_read_chunks' 'Mach 读取未使用部分完成契约'
Require-Text 'lara/kexploit/wzmem.m' 'wz_mcache_open\(256\)' '外读采集仍使用单页抖动缓存'
Require-Text 'lara/kexploit/wzmem.m' 'if \(objectOrDelta == 0\) return;' '对象为空的合法 pmap entry 仍会耗尽映射失败预算'
Require-Text 'lara/kexploit/TaskRop/vm.m' 'object->entryOffset \+ PAGE_SIZE' 'mapped-pages 仍按整个 Unity vm_object 创建 named entry'
Require-Text 'lara/kexploit/TaskRop/vm.m' 'entry\.vme_offset = object->objectOffset;' 'mapped-pages 偏移语义偏离已验证 DarkSword 路径'
Require-Text 'lara/kexploit/wzmem.m' 'tried >= 8192 \|\| failed >= 256' 'mapped-pages UnityFramework 扫描仍会过早退出'
Require-Text 'lara/kexploit/wzmem.m' 'image UUID scan exhausted' 'UnityFramework UUID 扫描失败缺少诊断'
Require-Text 'lara/kexploit/wzmem.m' 'extern kern_return_t mach_vm_read_overwrite' 'iOS SDK 缺少 Mach 读取声明兜底'
Require-Text 'lara/kexploit/wzmem.m' 'extern kern_return_t mach_vm_region_recurse' 'iOS SDK 缺少 Mach region 声明兜底'
Require-Text 'lara/kexploit/wzmem.m' 'magic == MH_MAGIC_64' '内核 Mach-O 魔数自检被改名污染'
Require-Text 'lara/classes/laramgr.swift' 'let canWrite = false' 'WZ 未保持版本级写权限 fail-closed'
Require-Text 'lara/classes/laramgr.swift' '@Published var wzShowAvatar: Bool = true' 'Core 默认绘制开关被 Swift 状态覆盖'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_set_transport_state' '连接状态未传给控制面板'
Require-Text 'lara/classes/laramgr.swift' 'func prepareWZEnvironment\(' 'Core 初始化页未接完整环境准备链'
Require-Text 'lara/classes/laramgr.swift' 'func wzCollectorPagesReadable\(' '连接成功前未验证王者关键采集页'
Require-Text 'lara/classes/laramgr.swift' 'imageValid && profileReadable' '采集页失败仍可能伪装连接成功'
Require-Text 'lara/classes/laramgr.swift' 'showWZControlPanel = false\s*setGameHUD\(true\)[\s\S]{0,500}wzhud_prepare_game_launch\(\)' '游戏启动前未先创建并验证 Core HUD'
Require-Text 'lara/classes/laramgr.swift' 'func setGameHUD\(_ enabled: Bool\)[\s\S]{0,1400}let requested = wzhud_set_enabled\(true\)' '显式 HUD 开关未保留唯一窗口创建入口'
Require-Text 'lara/kexploit/wzesp.h' 'WZESP_SHOW_MAP_ADJUSTMENT' '缺少独立地图调节显示开关'
Require-Text 'lara/kexploit/wzesp.h' 'WZESP_SHOW_SKILL' '缺少技能页读取开关'
Require-Text 'lara/kexploit/wz/YuanbaoCollector.mm' '_logicVisible=0x505, _meshVisible=0x506, _inCamera=0x507' '缺少王者只读视野字段链'
Require-Text 'lara/kexploit/wz/YuanbaoCollector.mm' 'header\.camp != host\.camp' '英雄敌我分类未接 camp'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'item\.primitive == WZESP_PRIMITIVE_MONSTER_POINT' '野怪点位和实体未独立过滤'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'item\.primitive == WZESP_PRIMITIVE_SOLDIER_POINT' '兵线点位和实体未独立过滤'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_wzPortraitRecallRings' '回城动态光环未接入'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'monster_marker_color\(item\.monsterSubtype\)' '野怪分类样式未接入'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '10000 \+ \(NSInteger\)__builtin_ctz\(flag\)' 'HUD 高位开关仍可能与滑块 tag 冲突'
Require-Text 'lara/kexploit/wz/WZYuanbaoDrawPolicy.h' 'kRecallSpinRadiansPerSecond = 7\.854f' '未同步元宝回城旋转参数'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'snapshotGeneration = g_wzSnapshotGeneration\.load\(\)[\s\S]*apply_wz_snapshot_main[\s\S]*snapshotGeneration != g_wzSnapshotGeneration\.load\(\)[\s\S]*hide_wz_items_main\(\)' '并发断开可能让旧快照覆盖最后清空帧'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'preferredFramesPerSecond = 60' '游戏绘制未接 Core 2.2 的 60 FPS 帧驱动'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'WZESP_SHOW_AVATAR \| WZESP_SHOW_HEALTH \| WZESP_SHOW_RECALL' 'Core 默认绘制开关未同步'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'WZHUDMetalCanvas' '游戏画布未按 Core QXA110 使用独立 UIView 宿主'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'NSClassFromString\(@"CAMetalLayer"\)' '游戏画布未按 Core QXA110 使用 CAMetalLayer'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_canvas\.autoresizingMask = UIViewAutoresizingFlexibleWidth \|[\s\S]*UIViewAutoresizingFlexibleHeight' 'Core QXA110 视觉层缺少宽高自动调整 mask=18'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_canvas\.multipleTouchEnabled = NO' 'Core QXA110 视觉层未关闭多点触摸'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'CGFloat scale = MIN\(1\.0, MIN\(CGRectGetWidth\(bounds\) / 900\.0,[\s\S]*CGRectGetHeight\(bounds\) / 600\.0\)\)' '控制台仍未按 Core 固定 900x600 画布使用完整逻辑边界缩放'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'dlsym\([\s\S]*"MTLCreateSystemDefaultDevice"' 'Core Metal 画布仍没有真实设备'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'newCommandQueue' 'Core Metal 画布仍没有命令队列'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'nextDrawable' 'Core Metal 画布仍未获取 drawable'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'presentDrawable:drawable' 'Core Metal 画布仍未持续提交 drawable'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'update_fallback_snapshot_main' 'Core 后台未接离屏 fallback 图层'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'drawViewHierarchyInRect:destination' 'UIKit 控制面板未直接进入 fallback 图像'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'snapshot_has_visible_pixels' 'fallback 图像未检查真实像素内容'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'nonzeroSamples >= 8' '全透明 fallback 仍可能伪报成功'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'update_fallback_snapshot_main\(NO\)' '完整绘制模式未预生成可见 fallback 快照'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'validatedMask = kWZHUDFloatContextMask' 'fallback 空白时未降级到独立浮球 context'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_active\.store\(true\);[\s\S]{0,180}BOOL firstFramePresented = present_metal_frame_main\(\)' 'HUD 未先进入活动状态再异步等待 Core Metal 首帧'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!present_metal_frame_main\(\)\)[\s\S]{0,300}g_active\.store\(false\)' '首个 drawable 暂不可用时仍会关闭三窗口并阻断启动游戏'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'bool wzhud_is_enabled\(void\)[\s\S]{0,500}g_metalSurfaceHealthy\.load\(\)' 'HUD 活动状态仍错误依赖同步拿到首个 Metal drawable'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_metalFallbackLayer\.contents = ' '后台 fallback 图像未提交到保活 CALayer'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL fallbackVisible = captured && g_metalFallbackLayer[\s\S]*g_metalFallbackLayer\.hidden = NO[\s\S]*surface=fallback' 'Metal drawable 持续为空时仍未把 Core 普通图层切为可见 surface'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_fallbackPresentedFrames\.fetch_add\(1\)' '缺少 fallback surface 实际显示计数'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_metalFallbackLayer\.zPosition = 1000\.0[\s\S]*\[metalLayer addSublayer:g_metalFallbackLayer\]' 'fallback 未对齐 Core QXA110.qp408 的 CAMetalLayer 内部 z=1000 层级'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_renderSurfaceLayer\.zPosition = 10\.0[\s\S]*\[drawRootLayer addSublayer:g_renderSurfaceLayer\]' '缺少 Core qp420 外部普通渲染层'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL shouldUseDrawable = g_sceneActive\.load\(\);[\s\S]*shouldUseDrawable &&[\s\S]*present_snapshot_metal_frame_main\(\)' '后台仍会请求 nextDrawable，未按 Core QXA120 直连状态进入 offscreen fallback 路径'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'drawableAttempted=%d parentMetal=%d' 'fallback 运行日志无法证明后台 drawable 门禁和 CAMetalLayer 父层级'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '\[g_canvas addSubview:g_panel\]' 'Core 菜单视觉层仍未挂在持续提交的 Metal 画布'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '\[controlRoot addSubview:g_panelInputProxy\]' 'Core 中层窗口缺少透明输入代理'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'controlRoot\.multipleTouchEnabled = YES;[\s\S]*controlRoot\.clipsToBounds = YES;[\s\S]*floatRoot\.multipleTouchEnabled = YES;[\s\S]*floatRoot\.clipsToBounds = YES;' '控制/浮球根视图属性未对齐 Core qm531'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_panelInputProxy\.hidden = !visible' '视觉菜单与输入代理显示状态未同步'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'colorWithWhite:0\.0 alpha:0\.012' 'Core 输入层缺少保持 context 的极低透明度像素'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@implementation WZHUDTouchProxy[\s\S]*touchesBegan:[\s\S]*touchesMoved:[\s\S]*touchesEnded:[\s\S]*touchesCancelled:' '输入代理仍使用手势猜测，未对齐 Core QXA112 原始触摸链'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_panelInputProxy\.multipleTouchEnabled = NO' 'Core QXA112 输入代理未关闭多点触摸'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'directControlGesture:' '视觉面板仍挂载重复手势链，可能与 QXA112 原始触摸重复触发'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_window\.userInteractionEnabled = NO' 'Core 最低绘制窗口仍参与 UIKit 命中'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' '\[(root|controlRoot) addSubview:g_panel\]' '菜单视觉层仍错误放在中间控制窗口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'convertPoint:point fromView:g_panel' '控制台嵌套控件仍混用局部与面板坐标'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_actionCallback' '原生 Core 控制台未接初始化和启动动作'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'handle_panel_pointer_main\(panelPoint, pointerPhase\)' '全局 HID 完整触摸阶段未转发给控制台'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'WZHUDPointerPhaseBegan' '控制台缺少触摸按下阶段'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'WZHUDPointerPhaseMoved' '控制台缺少触摸移动阶段'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'move_float_button_main' 'Core 浮球没有拖动链'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_floatButton = \[UIButton buttonWithType:UIButtonTypeCustom\]' 'Core 浮球仍不是原版 UIButton'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'UIControlEventTouchUpInside' 'Core 浮球点击未使用 touch-up-inside'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'floatPan\.maximumNumberOfTouches = 1' 'Core 浮球拖动未限制为单指'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'setObject:NSStringFromCGPoint\(g_floatSavedCenter\)' '浮球位置未按 Core CGPoint 字符串持久化'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_floatButton\.hidden = NO' '菜单显示时仍会隐藏 Core 顶层浮球'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'sceneActive \|\| g_contextsStable\.load\(\)' '浮球和菜单输入未按 Core 前台或 context 稳定状态门控'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'IOHIDEventSystemClientCreate' '全局触摸未以 Core IOHID client 为首选'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'IOHIDEventSystemClientRegisterEventCallback' '全局触摸未注册 Core IOHID 回调'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'IOHIDEventSystemClientScheduleWithRunLoop' 'Core IOHID client 未调度到主运行循环'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_wzSkillPortraits' '技能冷却仍未使用固定英雄栏'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'item\.auxiliaryCooldownSeconds' '辅助技能冷却未进入绘制层'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'URLForResource:@"heroatlas"' 'HUD 未接入王者英雄头像图集'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'error=%s' 'HUD 创建失败没有输出可诊断日志'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@interface WZHUDDrawWindow : UIWindow' '缺少 Core 绘制系统窗口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@interface WZHUDControlWindow : UIWindow' '缺少 Core 独立控制系统窗口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@interface WZHUDFloatWindow : UIWindow' '缺少 Core 顶层浮球系统窗口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'canBecomeKeyWindow \{ return NO; \}' 'HUD 窗口未同步 Core 非 key-window 语义'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '_isSystemWindow \{ return YES; \}' 'HUD 窗口未同步 Core system-window 语义'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '_isWindowServerHostingManaged \{ return NO; \}' 'HUD 窗口未同步 Core hosting 语义'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '_shouldCreateContextAsSecure \{ return NO; \}' 'HUD 窗口未同步 Core context 语义'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '_ignoresHitTest \{ return YES; \}' 'Core 绘制窗口未保持穿透'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@implementation WZHUDControlWindow[\s\S]*_ignoresHitTest \{ return NO; \}' 'Core 控制窗口仍忽略 UIKit 点击'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!insideControl\) return nil;' '控制窗口未按面板范围选择性命中'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'return \[super hitTest:point withEvent:event\];' '控制窗口未把面板点击交给 UIKit'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' '_setAllWindowsKeepContextInBackground:|g_backgroundWindowPolicyReady' '错误把 Core _NXV2 的全局窗口策略提升为 QXA105 菜单门禁'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'setDisableUpdateMask:' '缺少 Core 后台图层保活接口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'set_layer_disable_update_mask_main\([\s\S]*g_renderSurfaceLayer[\s\S]*set_layer_disable_update_mask_main\(g_canvas\.layer[\s\S]*set_layer_disable_update_mask_main\(g_floatButton\.layer' '后台图层 mask 未限制为绘制面、画布和浮球层'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'set_layer_disable_update_mask_main\(g_metalFallbackLayer' '错误地给 QXA110 内部 fallback 子层单独施加 update mask'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'configure_background_layer_masks_main\(0x12\)' 'HUD 创建和恢复时未启用 Core 图层保活掩码'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'configure_background_layer_masks_main\(0\)' 'HUD 销毁时未清理 Core 图层保活掩码'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL floatReady = present_float_window_main\(\);\s*BOOL layerMaskReady = configure_background_layer_masks_main\(0x12\);\s*BOOL firstPublish = g_window\.hidden;\s*BOOL contentReady = update_fallback_snapshot_main\(YES\);[\s\S]*?g_window\.hidden = NO;' '完整绘制窗口首次可见前未完成浮球、菜单像素和图层掩码'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_window\.userInteractionEnabled = NO;\s*[\s\S]*?g_window\.hidden = YES;\s*g_controlWindow\.rootViewController' 'Core 绘制窗口仍在内容和掩码就绪前提前显示'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'CGRectGetMaxX\(initialSurface\) \+ 32\.0,[\s\S]*?CGRectGetMaxY\(initialSurface\) \+ 32\.0, 1\.0, 1\.0' 'Core 控制和浮球窗口未使用 qm531 的离屏 1x1 首次提交几何'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'apply_panel_visibility_state_main\(YES\);[\s\S]*rebuild_core_page_main\(\);[\s\S]*present_hud_windows_main\(\)' 'Core 菜单仍在绘制窗口首次可见之后才打开'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'panelFrame = \[g_panel convertRect:g_panel\.bounds toView:g_window\];[\s\S]*g_controlWindow\.frame = panelFrame' '交互窗口未缩到 Core 面板实际命中区域'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_floatWindow\.frame = floatFrame' '浮球窗口未缩到 Core 浮球实际命中区域'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL ready = g_windowContextIDs\[2\] != 0 &&[\s\S]*g_floatButton\.window == g_floatWindow &&[\s\S]*!g_floatWindow\.hidden && !g_floatButton\.hidden' '独立浮球就绪状态未绑定可见窗口、context 与 ownership'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL ready = maskReady &&' '私有 layer mask 失败仍会误杀独立浮球'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'g_controlWindow\.frame = physical|g_floatWindow\.frame = physical' '交互窗口仍错误占满整个物理屏幕'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!metalRendererReady \|\| !backgroundLayerMaskReady\)[\s\S]*g_window\.hidden = YES;\s*g_controlWindow\.hidden = YES;[\s\S]*g_active\.store\(true\)' 'Metal 或绘制首帧失败时未保留独立浮球降级'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!metalRendererReady\)[\s\S]{0,400}g_floatWindow\.hidden = YES' 'Metal 初始化失败仍会连带隐藏独立浮球'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!metalRendererReady \|\| !backgroundLayerMaskReady\)' '完整绘制模式未继续检查图层保活结果'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_directInteractionEnabled = YES' '前台 UIKit 直接交互仍被禁用'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'bool wzhud_is_enabled\(void\)[\s\S]{0,240}g_active\.load\(\) && g_floatWindowReady\.load\(\)' 'HUD 活动状态仍未按独立浮球发布结果判断'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'bool wzhud_is_enabled\(void\)[\s\S]{0,300}g_(backgroundLayerMaskReady|firstCommitContentReady|metalRendererReady|floatLayerMaskReady)\.load\(\)' '独立浮球状态仍错误依赖绘制或私有 layer-mask 能力'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_controlWindow\.rootViewController = nil' '控制窗口销毁时未解除控制器'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_floatWindow\.rootViewController = nil' '浮球窗口销毁时未解除控制器'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'UISceneActivationStateForegroundActive' 'HUD 未绑定前台活动场景'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'kWZHUDWindowLevel = 10000000\.0' 'HUD 层级未按 Core 2.2 QXA105 常量同步'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'kWZHUDWindowLevel \+ 100\.0' 'Core 中层交互窗口未使用 10000100 层级'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'kWZHUDWindowLevel \+ 200\.0' 'Core 顶层浮球窗口未使用 10000200 层级'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'FBSOrientationObserver' '仍使用 Core 2.2 未导入的 FBS 方向观察器'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'UIApplicationDidEnterBackgroundNotification|UISceneWillEnterForegroundNotification|applicationStateChanged:' 'HUD 仍依赖通知推断 Core QXA120 的直接 scene 状态'
Require-Text 'lara/kexploit/WZHUDBridge.h' 'wzhud_scene_active_changed' '缺少 Core QXA120 场景状态桥'
Require-Text 'lara/lara.swift' 'sceneDidBecomeActive[\s\S]*wzhud_scene_active_changed\(true\)[\s\S]*sceneWillResignActive[\s\S]*wzhud_scene_active_changed\(false\)[\s\S]*sceneDidEnterBackground[\s\S]*wzhud_scene_active_changed\(false\)' 'SceneDelegate 未按 Core QXA120 直接传递前后台状态'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'viewWillTransitionToSize:' 'HUD 未接坐标空间变化后的重排'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_get_canvas_size\(&canvasWidth, &canvasHeight\)' '采集投影仍使用竖屏 UIScreen 尺寸'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'IOHIDEventSystemClientUnscheduleWithRunLoop' 'HUD 释放时未撤销 IOHID 调度'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'removeObserver:g_controller' 'HUD 释放时未移除生命周期观察'
$hudSource = Get-Content -LiteralPath (Join-Path $root 'lara/kexploit/WZHUDBridge.mm') -Raw
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'SBSAccessibilityWindowHostingController' '缺少 Core 隐藏的 SpringBoard 托管类'
Reject-Text 'lara/kexploit/TaskRop/RemoteCall.h' '@import Foundation' 'RemoteCall 公共头仍要求 Objective-C++ C++ modules'
Require-Text 'lara/kexploit/TaskRop/RemoteCall.h' '#import <Foundation/Foundation\.h>' 'RemoteCall 公共头缺少非 modules Foundation 导入'
Require-Text 'lara/kexploit/TaskRop/RemoteCall.h' 'extern "C" \{[\s\S]*remote_alloc_str[\s\S]*remote_sel[\s\S]*remote_getClass[\s\S]*remote_msg[\s\S]*\}' 'RemoteCall helper 未保持 C ABI，Objective-C++ 会链接失败'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'registerWindowWithContextID:atLevel:' '三窗口未使用 Core 的完整托管选择子'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'unregisterWindowWithContextID:' 'HUD 生命周期缺少 SpringBoard context 注销'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'methodSignatureForSelector:' 'SpringBoard 托管未通过真实 Objective-C 方法签名'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'objc_setAssociatedObject' '托管控制器未按 Core 生命周期保留'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'objc_getAssociatedObject' '托管控制器关联未读回验证'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'wzhud_remote_persistent_key[\s\S]*RemoteArbCall\(remoteCall, malloc, length\)' 'stack-fallback 下关联键仍会复用临时 scratch'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'trojanMemScratchOffset = scratchOffset' '远端 selector/class 临时字符串会耗尽单页 scratch'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'levels\[3\] = \{ 999998\.0, 999999\.0, 1000000\.0 \}' 'draw/menu/icon 托管层级未对齐 Core'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'registrationOrder\[3\] = \{ 0, 2, 1 \}' '托管调用顺序未对齐 Core draw/icon/menu'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!unregister_springboard_hosting_locked\(remoteCall\)\)[\s\S]*remote_create_hosting_controller' '重复注册前未注销旧 context'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(!registered\)[\s\S]*rollback_hosting_state_locked' '三窗口部分注册失败时未回滚'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(\(contextMask & \(1u << index\)\) == 0\) continue;' 'SpringBoard 托管未按验证后的 context mask 跳过不可用窗口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'hosting=retry mode=float after full registration failure' '完整三窗口注册失败后未重试独立浮球托管'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'remote_install_hosting_lifecycle\([\s\S]*contextMask, reason' '锁屏生命周期仍会强制创建三窗口 invocation'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'UIApplicationProtectedDataWillBecomeUnavailable' '缺少 Core 锁屏注销通知'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'UIApplicationProtectedDataDidBecomeAvailable' '缺少 Core 解锁恢复通知'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'okdemoDarkSwordDrawLockInvocation' '缺少 Core draw 锁屏 invocation 关联键'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'okdemoDarkSwordIconUnlockInvocation' '缺少 Core icon 解锁 invocation 关联键'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'addObserver:selector:name:object:' '锁屏生命周期 invocation 未安装到 SpringBoard 通知中心'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'removeObserver:' '注销托管时未移除 SpringBoard 生命周期观察者'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'commitValid = g_requested\.load\(\) && g_contextsStable\.load\(\)[\s\S]*g_validatedContextMask\.load\(\) == contextMask' '并发关闭或 context 模式变化时缺少托管提交前复核'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'commitValid = g_requested\.load\(\) && g_sceneActive\.load\(\)' '场景切后台仍会错误否定已验证的浮球 context'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_cancel_pending_hosting\(\)[\s\S]*wzhud_unregister_springboard_hosting\(process\)' '并发关闭未先失效托管提交再执行远端注销'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'refresh_window_context_ids_main' '缺少 Core 三窗口 context 诊断'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '\[CATransaction flush\]' '窗口切后台前没有完成 Core 显式事务刷新'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'handle_scene_activity_main\(BOOL active\)' 'HUD 未区分 Core 前后台窗口生命周期'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'if \(g_validatedContextMask\.load\(\) == kWZHUDFloatContextMask\)[\s\S]*g_window\.hidden = YES;\s*g_controlWindow\.hidden = YES;[\s\S]*g_displayLink\.paused = YES;[\s\S]*present_float_window_main\(\)[\s\S]*sceneState=%s mode=float[\s\S]*return;' 'float-only 模式切换场景时仍会重发完整绘制窗口'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL floatPreserved = wasStable && floatPresented &&[\s\S]*g_windowContextIDs\[2\] == previousFloatContext' 'float-only 场景切换未单独复核浮球 context'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'sceneState=active contextsPreserved=' '缺少前台 context 保留/重验诊断'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL contextsPreserved = wasStable && windowsPresented &&[\s\S]*g_windowContextIDs[\s\S]*schedule_context_validation_main\(\);' '前台恢复仍用 drawable 结果否定稳定 context，而非按窗口提交和 ID 变化重验'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL keepRendering = g_requested\.load\(\) && g_contextsStable\.load\(\)' '后台渲染未按 HUD 请求和 context 健康状态门控'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_displayLink\.paused = !keepRendering' '后台仍无条件暂停 Core Metal 提交'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'surface=fallback frames=' '缺少后台保留表面提交诊断'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'g_backgroundRenderTimer' '错误引入 Core 不使用的独立后台渲染 timer'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'present_snapshot_metal_frame_main' '后台仍未把 UI 像素提交到 Metal drawable'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'copyFromTexture:[\s\S]*presentDrawable:[\s\S]*commit' '后台 Metal 路径未执行 texture blit/present/commit'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL published = captured && shouldUseDrawable &&[\s\S]*present_snapshot_metal_frame_main\(\);[\s\S]*if \(!published\)[\s\S]*return NO;[\s\S]*g_metalPresentedFrames\.fetch_add\(1\)' 'Metal presented 计数未受 active drawable 真实提交结果门禁'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'BOOL retainedSurface = g_metalSurfaceHealthy\.load\(\) &&[\s\S]*g_contextsStable\.load\(\);[\s\S]*if \(retainedSurface\) return YES;' '后台 drawable 暂不可用时未保留最后一次前台提交表面'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'enable=idempotent active=1' '游戏 attach 后重复启用仍会在后台重建 HUD'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' 'MTLLoadActionClear' '前台仍向 Core Metal drawable 提交透明帧而非菜单像素'
Require-Count 'lara/classes/laramgr.swift' 'wzhud_set_enabled\(true\)' 1 'HUD 创建入口未限制在显式 setGameHUD，采集 attach 仍会重复创建'
Require-Text 'lara/classes/laramgr.swift' 'let requested = wzhud_is_enabled\(\)[\s\S]*self\.startWZLoop\(\)' '采集 attach 未只读取既有 HUD 状态'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'NSClassFromString\(@"CMMotionManager"\)' '缺少 Core 后台运动方向源'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'startDeviceMotionUpdatesToQueue:withHandler:' '未启动 Core 同款 device-motion 更新'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'setDeviceMotionUpdateInterval:[\s\S]*0\.2' 'device-motion 更新间隔未对齐 Core 0.2 秒'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '250 \* NSEC_PER_MSEC, 40 \* NSEC_PER_MSEC' '方向轮询未对齐 Core 250ms/40ms 合同'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'absX < 0\.55 \|\| absX <= absY' '横屏 gravity 判定未对齐 Core'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'UIInterfaceOrientationLandscapeLeft: return \(CGFloat\)M_PI_2;[\s\S]*UIInterfaceOrientationLandscapeRight: return \(CGFloat\)-M_PI_2;' '横屏旋转方向未对齐 Core QXA105.qm534'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'screen\.fixedCoordinateSpace\.bounds' '窗口物理边界未对齐 Core QXA105.qm535'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'stopDeviceMotionUpdates' 'HUD 释放时未停止 CoreMotion'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_orientationGeneration\.fetch_add\(1\)' '方向回调缺少断开代际失效保护'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'suspend_orientation_tracking_main\(\);[\s\S]*450 \* NSEC_PER_MSEC[\s\S]*install_orientation_observer_main\(\);' '450ms context 注册窗口未对齐 Core 的 qm556/qm555 方向冻结链'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'apply_orientation_main[\s\S]*\[CATransaction commit\][\s\S]*\[CATransaction flush\][\s\S]*refresh_window_context_ids_main\(\)' '方向更新未对齐 Core 的布局提交与 context 刷新链'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '450 \* NSEC_PER_MSEC' '缺少 Core context 450ms 稳定等待'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_contextValidationBaseline' '缺少三窗口 context 基线'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_validatedContextMask\.store\(validatedMask\);\s*g_contextsStable\.store\(validatedMask != 0\)' '完整或浮球 context 复核结果未进入启动门禁'
Require-Text 'lara/kexploit/WZHUDBridge.h' 'wzhud_prepare_game_launch' '启动链未暴露 Core context 准备接口'
Reject-Text 'lara/kexploit/WZHUDBridge.h' 'wzhud_install_process_window_policy' '头文件仍暴露不属于 QXA105 菜单链的全局窗口策略'
Require-Text 'lara/classes/laramgr.swift' 'guard wzhud_prepare_game_launch\(\)' '启动游戏未等待 Core context 准备'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_contexts_stable\(\)' '启动游戏未复核三窗口 context 稳定状态'
Require-Text 'lara/classes/laramgr.swift' 'rcinit\(process: "SpringBoard", migbypass: false\)' '启动链未建立 SpringBoard RemoteCall'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_register_springboard_hosting\(process\)' '稳定 context 未注册到 SpringBoard'
Require-Text 'lara/classes/laramgr.swift' 'guard hosted && wzhud_springboard_hosting_ready\(\)' 'SpringBoard 托管失败后仍可能启动游戏'
Require-Text 'lara/classes/laramgr.swift' 'guard epoch == wzLaunchEpoch,[\s\S]*wzhud_contexts_stable\(\),[\s\S]*wzhud_springboard_hosting_ready\(\)[\s\S]*UIApplication\.shared\.open' '打开游戏前未最终复核本地 context 与远端托管状态'
Require-Text 'lara/classes/laramgr.swift' 'let remoteProcess = sbProc\s*sbProc = nil[\s\S]*remoteProcess\?\.destroy\(\)' 'RemoteCall 销毁未先摘除共享引用'
Require-Text 'lara/classes/laramgr.swift' 'guard !wzSpringBoardHostingInFlight,[\s\S]*!wzhud_springboard_hosting_ready\(\)' '托管仍活动时 RemoteCall 仍可能被销毁'
Require-Text 'lara/classes/laramgr.swift' 'rcready = false\s*rcrunning = true[\s\S]*remoteProcess\?\.destroy\(\)[\s\S]*rcrunning = false' 'RemoteCall 销毁期间未阻止并发重建'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_unregister_springboard_hosting\(process\)[\s\S]*wzhud_set_enabled\(false\)' '关闭 HUD 时未先注销 SpringBoard context'
Require-Text 'lara/classes/laramgr.swift' 'wzLaunchEpoch &\+= 1' '关闭 HUD 未取消待执行的 context 验证/游戏启动'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'contexts=%u/%u/%u' '三窗口 context 缺少真机诊断'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'input=UIKit-active/HID-background' '缺少前后台输入路径诊断'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_titleLabel\.text = @"CORE\."' '缺少 Core 原版标题'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'static NSInteger g_selectedPage = 0' '游戏控制台首屏未落到主页'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"显示头像"' '缺少英雄页功能'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"显示野怪计时"' '缺少兵野页功能'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"显示英雄技能冷却"' '缺少技能页功能'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"显示小地图"' '缺少独立小地图开关'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"地图调节显示"' '缺少地图调节显示开关'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"地图坐标Y"' '缺少调整页功能'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"只读锁定"' '缺少只读状态提示'
Reject-Text 'lara/kexploit/WZHUDBridge.mm' '描边增强（写入）|目标追踪（写入）|自动瞄准（写入）' '控制台仍混入原版没有的写入入口'
Reject-Text 'lara/classes/laramgr.swift' 'requestWZWriteFeature|wzWriteGateReason' '状态层仍保留原版没有的写入占位功能'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'g_renderFPS\.load\(\)' '控制台仍显示硬编码帧率'
Require-Text 'lara/kexploit/WZHUDBridge.mm' '@"暗黑 \(Dark\)"' '控制台缺少可用暗色主题'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'wzCoreThemeColor' '主题色选择未持久化'
Require-Text 'lara/kexploit/WZHUDBridge.mm' 'detail\.frame = CGRectMake\(132, y' '主页状态值仍会被压缩成省略号'
Require-Text 'lara/views/app/ContentView.swift' 'Image\("core-mountain"\)' '应用首屏未接 Core 山景卡片'
Require-Text 'lara/views/app/ContentView.swift' '关闭菜单' '应用首屏未同步 Core 环形入口'
Require-Text 'lara/views/app/ContentView.swift' 'mgr\.launchWZGame\(\)' '启动游戏入口未接王者启动链'
Reject-Text 'lara/views/app/ContentView.swift' 'WZControlPanelView\(' '应用首屏仍叠加第二套 SwiftUI 控制台'
$duplicatePanel = Join-Path $root 'lara/views/app/WZControlPanelView.swift'
if (Test-Path -LiteralPath $duplicatePanel) {
    throw 'FAIL: 已停用的 SwiftUI 控制台副本仍留在构建源码中'
}
Reject-Text 'scripts/build_ipa_wz.sh' 'WZControlPanelView\.swift' '构建入口仍依赖已删除的重复控制台'
Require-Text 'lara.xcodeproj/project.pbxproj' 'INFOPLIST_KEY_UIRequiresFullScreen = YES' '应用未按 Core 2.2 保持全屏场景'
Require-Text 'lara.xcodeproj/project.pbxproj' 'INFOPLIST_KEY_UIApplicationSceneManifest_Generation = NO' '构建仍会覆盖 Core 单场景 manifest'
Require-Text 'lara/Info.plist' '<string>audio</string>' '应用未保留 Core 后台音频模式'
Require-Text 'lara/Info.plist' '<key>UIApplicationSupportsIndirectInputEvents</key>[\s\S]*<true/>' '应用未对齐 Core 间接输入合同'
Require-Text 'lara/Info.plist' '<key>UIRequiresFullScreen</key>[\s\S]*<true/>' '应用 Info.plist 未对齐 Core 全屏场景'
Require-Text 'lara/Info.plist' '<key>UISupportedInterfaceOrientations</key>[\s\S]*<string>UIInterfaceOrientationPortrait</string>' '应用 Info.plist 未对齐 Core 竖屏主场景'
Require-Text 'lara/Info.plist' '<key>UIApplicationSupportsMultipleScenes</key>[\s\S]*<false/>' '应用未对齐 Core 单场景模式'
Require-Text 'lara/Info.plist' '<key>UISceneDelegateClassName</key>[\s\S]*<string>LaraSceneDelegate</string>' '应用未显式绑定 UIKit SceneDelegate'
Reject-Text 'lara.xcodeproj/project.pbxproj' 'INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone = "[^\"]*Landscape' '应用主场景仍声明横屏方向'
if ((Get-Content -LiteralPath (Join-Path $root 'lara/views/app/ContentView.swift') -Raw) -match 'fullScreenCover') {
    throw 'FAIL: Core 控制台仍通过不透明 fullScreenCover 打开'
}
Require-Text 'lara/classes/laramgr.swift' 'func openWZControlPanel\(' '控制台入口未接初始化状态机'
Require-Text 'lara/classes/laramgr.swift' 'wzhud_set_panel_visible\(true\)' '控制台入口未打开单一 Core 系统面板'
Reject-Text 'lara/classes/laramgr.swift' 'requestGeometryUpdate' '应用场景仍偏离 Core 2.2 的竖屏掩码并强制横屏'
Require-Text '.github/workflows/build.yml' 'scripts/build_ipa_wz\.sh' 'CI 仍未使用王者构建入口'
Require-Text 'scripts/build_ipa_wz.sh' 'PlistBuddy.*LARABuildSourceCommit' '构建产物未写入源码提交标识'
Reject-Text 'scripts/build_ipa_wz.sh' 'for marker in _setAllWindowsKeepContextInBackground:' '打包脚本仍强制要求已从 QXA105 菜单链删除的全局窗口策略'
Require-Text 'scripts/build_ipa_wz.sh' 'firstCommitContent=' '打包脚本未验证首次菜单内容提交标记'
Require-Text 'scripts/build_ipa_wz.sh' 'sceneState=active' '打包脚本未验证 Core QXA120 Scene 直连标记'

$appSource = Get-Content -LiteralPath (Join-Path $root 'lara/lara.swift') -Raw
if ($appSource -match 'TabView\s*\(') {
    throw 'FAIL: 应用入口仍保留旧 TabView 外壳'
}
if ($appSource -match 'struct\s+lara\s*:\s*App|WindowGroup\s*\{') {
    throw 'FAIL: 应用入口仍由 SwiftUI 隐式多场景托管'
}
Require-Text 'lara/lara.swift' '@main[\s\S]*final class LaraAppDelegate: UIResponder, UIApplicationDelegate' '缺少 Core 同款 UIKit AppDelegate 入口'
Require-Text 'lara/lara.swift' '@objc\(LaraSceneDelegate\)[\s\S]*UIWindowSceneDelegate' '缺少显式单场景 SceneDelegate'
Require-Text 'lara/lara.swift' 'UIWindow\(windowScene: windowScene\)' 'SceneDelegate 未直接创建主 UIWindow'
Require-Text 'lara/lara.swift' 'UIHostingController\(rootView: LaraRootView\(\)\)' '现有 SwiftUI 页面未由 UIKit 场景承载'
Require-Text 'lara/lara.swift' 'didFinishLaunchingWithOptions[\s\S]*bootstrapLaraApplication\(\)[\s\S]*return true' 'UIKit 启动链未正常初始化 Lara'
Reject-Text 'lara/lara.swift' 'wzhud_install_process_window_policy' 'AppDelegate 仍被不属于 Core QXA105 的全局策略阻断'
Require-Text 'lara/lara.swift' 'wzSpringBoardHostingInFlight \|\|[\s\S]*wzhud_springboard_hosting_ready\(\)' '后台切换仍会并发销毁正在使用的 SpringBoard RemoteCall'

$atlas = Join-Path $root 'lara/heroatlas.bin'
if (-not (Test-Path -LiteralPath $atlas) -or (Get-Item -LiteralPath $atlas).Length -ne 2164890) {
    throw 'FAIL: 王者英雄头像图集缺失或长度不符'
}
$atlasHash = (Get-FileHash -LiteralPath $atlas -Algorithm SHA256).Hash
if ($atlasHash -ne '32061154E6545F5372C567BD0598AFBAE815E18EAA80B1F4247C218FB3FB913E') {
    throw 'FAIL: 王者英雄头像图集哈希不符'
}

$launcher = Join-Path $root 'lara/core-mountain.png'
if (-not (Test-Path -LiteralPath $launcher) -or (Get-Item -LiteralPath $launcher).Length -lt 500000) {
    throw 'FAIL: Core 启动页山景资产缺失或无效'
}

Write-Output 'PASS: WZ/Core static contracts present; build and device parity remain unverified'
